services:
  journal-api:
    build: .
    container_name: journal-api
    restart: unless-stopped
    ports:
      - 8008:8000
    volumes:
      - /mnt/Main/journal:/data
    environment:
      JOURNAL_DB: /data/journal.db
networks: {}
